name:                statusline
version:             0.1.0.0
github:              "jacksoncooper/statusline"
author:              "Jackson Cooper"
maintainer:          "jacksoncooper@users.noreply.github.com"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: A statusline program for use with sway-bar.

dependencies:
- base >= 4.7 && < 5
- time >= 1.9.3

library:
  source-dirs: src

executables:
  statusline-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - statusline
